#!/usr/bin/env bash

ATS_USER_HOME=/home/atsuser
mkdir -p $ATS_USER_HOME/work
cd $ATS_USER_HOME/work


# currently not deployed: HTTPDBLOGGER_VERSION="4.0.11-SNAPSHOT"
# unzip options - quiet, do not list each extracted file
UNZIP=-q; export UNZIP

TOMCAT_VER=9.0.63
TOMCAT_DOWNLOAD_LOCATION="http://archive.apache.org/dist/tomcat/tomcat-9/v${TOMCAT_VER}/bin/apache-tomcat-${TOMCAT_VER}.zip"
TOMCAT_ZIP_NAME=`echo $TOMCAT_DOWNLOAD_LOCATION | awk '{len=split($0,a,"/"); print a[len]}'`
TOMCAT_NAME=`echo $TOMCAT_ZIP_NAME | awk '{len=split($0,a,".zip"); print a[len-1]}'`
TOMCAT_HOME=$ATS_USER_HOME/work/tomcat

TESTEXPLORER_HOME=$ATS_USER_HOME/work/testexplorer
#TE_DOWNLOAD_LOCATION="https://oss.sonatype.org/content/groups/public/com/axway/ats/testexplorer/ats-testexplorer/$TESTEXPLORER_VERSION"
TESTEXPLORER_METADATA=$TE_VERSION

echo "-- Starting TestExplorer-related downloads from $TE_DOWNLOAD_LOCATION"
wget --no-check-certificate -O testexplorer-maven-metadata.xml $TE_DOWNLOAD_LOCATION/maven-metadata.xml
WGET_STATUS=$?
if [ $WGET_STATUS -eq 0 ]
then
  echo "Wget - successfully downloaded TestExplorer maven-metadata.xml."
else
  echo "Failed to download maven-metadata.xml for TestExplorer"
  exit 3
fi

if [ -s "testexplorer-maven-metadata.xml" ];
then
  TESTEXPLORER_METADATA=`cat testexplorer-maven-metadata.xml | grep 'value' | uniq | xargs | awk '{n=split($0,a,">"); print a[n-1]}' | awk '{n=split($0,a,"<"); print a[1]}'`
  rm testexplorer-maven-metadata.xml
  echo "Parsed latest snapshot version: $TESTEXPLORER_METADATA"
  if [[ -z "$TESTEXPLORER_METADATA" ]]
  then
     echo "Could not parse version. Stop build"
     exit 2
  fi
else
    echo "Assume non-SNAPSHOT version: $TESTEXPLORER_METADATA because maven-metadata.xml is not found."
fi

### HTTP Db Logger section - optional
#HTTPDBLOGGER_HOME=$ATS_USER_HOME/work/httpdblogger
#HTTPDBLOGGER_DOWNLOAD_LOCATION="https://oss.sonatype.org/content/groups/public/com/axway/ats/httpdblogger/ats-httpdblogger/$HTTPDBLOGGER_VERSION"
#HTTPDBLOGGER_METADATA=$HTTPDBLOGGER_VERSION
#
#wget -O httpdblogger-maven-metadata.xml $HTTPDBLOGGER_DOWNLOAD_LOCATION/maven-metadata.xml
#if [ -s "httpdblogger-maven-metadata.xml" ]; # file exists and its size is > 0
#then
#    HTTPDBLOGGER_METADATA=`cat httpdblogger-maven-metadata.xml | grep 'value' | uniq | xargs | awk '{n=split($0,a,">"); print a[n-1]}' | awk '{n=split($0,a,"<"); print a[1]}'`
#    rm httpdblogger-maven-metadata.xml
#fi

# download Tomcat
if [ ! -d "$TOMCAT_HOME" ];
then
    mkdir $TOMCAT_HOME
fi
cd $TOMCAT_HOME

wget $TOMCAT_DOWNLOAD_LOCATION
unzip $TOMCAT_ZIP_NAME
rm $TOMCAT_ZIP_NAME
mv $TOMCAT_NAME/* .
rm -r $TOMCAT_HOME/webapps/examples/ $TOMCAT_HOME/webapps/docs/
chmod ug+x $TOMCAT_HOME/bin/catalina.sh

# config tomcat
rm -rf $TOMCAT_HOME/webapps/ROOT/*
cat <<EOF > $TOMCAT_HOME/webapps/ROOT/index.html
<html>

<head>
<meta http-equiv="refresh" content="0;URL=/TestExplorer/">
</head>

<body>
</body>
EOF

# download TestExplorer
if [ ! -d "$TESTEXPLORER_HOME" ];
then
    mkdir -p $TESTEXPLORER_HOME
fi
cd $TESTEXPLORER_HOME
wget --no-check-certificate "$TE_DOWNLOAD_LOCATION/ats-testexplorer-$TESTEXPLORER_METADATA.zip"
unzip ats-testexplorer-$TESTEXPLORER_METADATA.zip
rm ats-testexplorer-$TESTEXPLORER_METADATA.zip
# deploy TestExplorer - unpacked in webapps for easy runtime/on-start reconfiguration
unzip *.war -d $TOMCAT_HOME/webapps/TestExplorer/

# TestExplorer - once unpack and replace logging server and DB on each start

cd $ATS_USER_HOME/work

# Optional - HttpDbLogger deployment
## download http db logger
#if [ ! -d "$HTTPDBLOGGER_HOME" ];
#then
#    mkdir $HTTPDBLOGGER_HOME
#fi
#cd $HTTPDBLOGGER_HOME
#wget "$HTTPDBLOGGER_DOWNLOAD_LOCATION/ats-httpdblogger-$HTTPDBLOGGER_METADATA.war"
## deploy http db logger
#mv *.war $TOMCAT_HOME/webapps/HttpDbLogger.war

# do not ask for password, when user 'atsuser' executes sudo
echo "atsuser ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/dont-prompt-atsuser-for-password
