#!/usr/bin/env bash
# Run container and keep console logs in current console. Ctrl-C to stop it
. ./env.sh

docker run -it -p 8080:8080 \
    --env-file ./$ENV_CONT_FILE_NAME \
    --name="$CONT_ID" $IMAGE_NAME
